name: Docker Image CI

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
   push:
     tags:
       - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and tag Docker image
      run: |
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TAG_NAME=${GITHUB_REF#refs/tags/}   # ejemplo: v1.0.0
        IMAGE_BASE=ghcr.io/${REPO_LOWER}/api

        echo "Building $IMAGE_BASE with tags: $TAG_NAME and latest"

        # Construye la imagen con ambas tags
        docker build --no-cache \
          -t $IMAGE_BASE:$TAG_NAME \
          -t $IMAGE_BASE:latest \
          -f Backend/API/Dockerfile Backend

    - name: Push Docker image to GitHub Container Registry
      run: |
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        TAG_NAME=${GITHUB_REF#refs/tags/}
        IMAGE_BASE=ghcr.io/${REPO_LOWER}/api

        echo "Pushing $IMAGE_BASE:$TAG_NAME"
        docker push $IMAGE_BASE:$TAG_NAME

        echo "Pushing $IMAGE_BASE:latest"
        docker push $IMAGE_BASE:latest
