name: Build Validation

on:
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Backend/Backend.sln
    
    - name: Build
      run: dotnet build Backend/Backend.sln --configuration Release --no-restore
